blank_issues_enabled: false
contact_links:
  - name: Leliuga Authors Support
    url: https://github.com/leliuga/.github/discussions
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!