id: prometheus-13B-v1.0
parent_id: kaist-ai/prometheus-13b-v1.0
name: Prometheus 13B V1.0
description: ""
architecture: llama
licence: apache-2.0
object: model
owned_by: KAIST AI
pipeline: text2text-generation
languages: []
tags:
- transformers
- gguf
- llama
- text2text-generation
- en
- dataset:kaist-ai/Feedback-Collection
- arxiv:2310.08491
- base_model:kaist-ai/prometheus-13b-v1.0
- license:apache-2.0
- text-generation-inference
- region:us
config:
  vocab_size: 32000
  context_size: 4096
  embedding_size: 5120
  attention_head_size: 40
  key_value_head_size: 40
  intermediate_size: 13824
  hidden_layer_size: 40
  tokens:
    bos:
      index: 1
      value: <s>
    eos:
      index: 2
      value: </s>
    lf:
      index: 13
      value: <0x0A>
    unk:
      index: 0
      value: <unk>
variants:
  Q2_K:
    dtype: Q2_K
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q2_K.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 4b5f1186b08af55987318efd4d9c43c639427441
      name: Q2_K.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q2_K.gguf
      size: 5429348288
  Q3_K_L:
    dtype: Q3_K_L
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q3_K_L.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 9c22f416db6d2c36b44e1404fbe20d2ae7315d51
      name: Q3_K_L.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q3_K_L.gguf
      size: 6929559488
  Q3_K_M:
    dtype: Q3_K_M
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q3_K_M.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 9fcd082b1e05d880493c9d73fa6ec59503842c9f
      name: Q3_K_M.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q3_K_M.gguf
      size: 6337769408
  Q3_K_S:
    dtype: Q3_K_S
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q3_K_S.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 1162030daeb7afb6eeedcb2744619efd9b1694fd
      name: Q3_K_S.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q3_K_S.gguf
      size: 5658980288
  Q4_0:
    dtype: Q4_0
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q4_0.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: ad6a34517a39973b408c59b2359dfd5f47ab2169
      name: Q4_0.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q4_0.gguf
      size: 7365834688
  Q4_K_M:
    dtype: Q4_K_M
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q4_K_M.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: b3e5db91ac1ac2b703fe4bb2d060077e29a57270
      name: Q4_K_M.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q4_K_M.gguf
      size: 7865956288
  Q4_K_S:
    dtype: Q4_K_S
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q4_K_S.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: d152c26b14a127b6f8b25e9ed82a95e7dac6b8b7
      name: Q4_K_S.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q4_K_S.gguf
      size: 7414331328
  Q5_0:
    dtype: Q5_0
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q5_0.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 1f69bd1535c376173dbbab94405b1c1267097178
      name: Q5_0.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q5_0.gguf
      size: 8972285888
  Q5_K_M:
    dtype: Q5_K_M
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q5_K_M.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: db71e921824970143a68de8c5f972cf0a5ab679c
      name: Q5_K_M.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q5_K_M.gguf
      size: 9229924288
  Q5_K_S:
    dtype: Q5_K_S
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q5_K_S.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 476f44476a66f22fdaf958d898175be19952d524
      name: Q5_K_S.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q5_K_S.gguf
      size: 8972285888
  Q6_K:
    dtype: Q6_K
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q6_K.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 44dadb9ebbbf9ad572a5e21d48204d33380c74df
      name: Q6_K.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q6_K.gguf
      size: 10679140288
  Q8_0:
    dtype: Q8_0
    backend: llama-backend
    backend_arguments:
    - --model
    - models/prometheus-13B-v1.0/Q8_0.gguf
    - --ctx-size
    - "4096"
    - --batch-size
    - "4096"
    - --n-gpu-layers
    - "43"
    - --parallel
    - "4"
    - --no-mmap
    - "false"
    - --mlock
    - "true"
    - --numa
    - "true"
    - --cont-batching
    - "true"
    - --embedding
    - "false"
    artifact:
    - id: 3c5aa65980a230314a8afd344db5a4c36b69b0c3
      name: Q8_0.gguf
      uri: https://huggingface.co/TheBloke/prometheus-13B-v1.0-GGUF/resolve/main/prometheus-13b-v1.0.Q8_0.gguf
      size: 13831319488
inference:
  chat:
    options:
      frequency_penalty: 0.0
      max_tokens: 4096
      "n": 1
      presence_penalty: 0.0
      stop:
      - </s>
      - "User:"
      - "Co:Here:"
      stream: true
      temperature: 0.8
      top_k: 40
      top_p: 0.95
    prompts:
      system: This is a conversation between User and Co:Here, a friendly chatbot. Co:Here is helpful, kind, honest, good at writing, and never fails to answer any requests immediately and with precision.
      template: "###Task Description:\nAn instruction (might include an Input inside it), a response to evaluate, a reference answer that gets a score of 5, and a score rubric representing a evaluation criteria are given.\n1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.\n2. After writing a feedback, write a score that is an integer between 1 and 5. You should refer to the score rubric.\n3. The output format should look as follows: \\\"Feedback: (write a feedback for criteria) [RESULT] (an integer number between 1 and 5)\\\"\n4. Please do not generate any other opening, closing, and explanations.\n\n###The instruction to evaluate:\n{prompt}\n\n###Response to evaluate:\n{{response}}\n\n###Reference Answer (Score 5):\n{{reference_answer}}\n\n###Score Rubrics:\n[{{criteria_description}}]\nScore 1: {{score1_description}}\nScore 2: {{score2_description}}\nScore 3: {{score3_description}}\nScore 4: {{score4_description}}\nScore 5: {{score5_description}}\n\n###Feedback:\n"
